name: Dummy Workflow

on:
  # Trigger on push to main branch
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run in'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Print environment
        run: |
          echo "Running in environment: ${{ github.event.inputs.environment || 'dev' }}"
          echo "Current time: $(date)"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: List directory contents
        run: |
          echo "Current directory contents:"
          ls -la

      - name: Dummy step with condition
        if: github.event.inputs.environment == 'prod'
        run: echo "This step only runs in production environment"

      - name: Always run step
        run: echo "This step always runs regardless of environment"